### ISSUE TITLE
Doesn't ascend

### ISSUE THREAD

**Issue by macmil** [sgoertzen/heroic-clicker#3]
There was an update to ascension confirmation screen layout (Steam version at least) and the bot cannot handle it.

**Comment by sgoertzen** [comment]
I updated the program and did a new build here: https://www.dropbox.com/s/03jeq0xysf940rg/Release.4.3.zip?dl=0

You can also grab the latest from source as that has been updated as well.

Are you able to confirm that it is fixed with this new build?  If so I will push this updated release to GitHub.

**Comment by macmil** [comment]
Still didn't Ascend. Fails to click on the ascend upgrade.
There is now a button below auto progression mode that has the same effect. It's visible once you have 200 Inhoteps

**Comment by RejectKid** [comment]
I've tried to push up a pull request for this fix but it seems im denied permission if youd like me to lemme know

**Comment by sgoertzen** [comment]
Not sure what I need to change on the repo to allow pull requests.  I
thought it was turned on by default but maybe now.

Did you follow the instructions here:
https://help.github.com/articles/using-pull-requests/?

**Comment by RejectKid** [comment]
figured it out i believe

**Comment by sgoertzen** [comment]
Merged your Pull Request in.  Thanks for the fixes!
